# Generated by Django 2.2.6 on 2019-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customer_id',
            field=models.CharField(default='001', max_length=6),
            preserve_default=False,
        ),
    ]
