# Generated by Django 2.2.6 on 2019-10-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_customerprofile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
