# Generated by Django 2.2.6 on 2019-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191015_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_id',
            field=models.CharField(max_length=6),
        ),
    ]
