# Generated by Django 2.2.6 on 2019-10-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='nearby_location',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
