# Generated by Django 2.2.6 on 2019-10-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_nearby_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='nearby_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
