# Generated by Django 2.2.6 on 2019-10-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20191016_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
